import { describe, expect, it } from 'vitest';

import { chunkBytes } from '../src/chunking.js';
import { digestChunkSync } from '../src/dedup.js';
import { REFERENCE_POINTER_BYTES } from '../src/delta.js';
import {
  generateReactionCorpus,
  generateReencodeVariants,
  generateRenditionLadder,
  MediaCorpusError,
} from '../src/media-corpus.js';
import { DEFAULT_MAX_CHAIN_DEPTH, NetworkStore, NetworkStoreError } from '../src/network-store.js';

/**
 * splitmix32, duplicated here on purpose.
 *
 * The test's inputs must not be produced by the same code path the library uses, or a bug in that
 * generator would be invisible: a store that round-trips a corpus generated by a broken generator
 * still round-trips. Twelve lines of duplication buys independence.
 */
function noise(length: number, seed: number): Uint8Array {
  let state = seed >>> 0;
  const next = (): number => {
    state = (state + 0x9e37_79b9) >>> 0;
    let z = state;
    z = Math.imul(z ^ (z >>> 16), 0x21f0_aaad) >>> 0;
    z = Math.imul(z ^ (z >>> 15), 0x735a_2d97) >>> 0;
    return (z ^ (z >>> 15)) >>> 0;
  };
  const bytes = new Uint8Array(length);
  for (let index = 0; index < length; index += 1) {
    bytes[index] = next() & 0xff;
  }
  return bytes;
}

function repeating(length: number, period: number): Uint8Array {
  const bytes = new Uint8Array(length);
  for (let index = 0; index < length; index += 1) {
    bytes[index] = index % period;
  }
  return bytes;
}

function expectExactRoundTrip(store: NetworkStore, input: Uint8Array, label: string): void {
  const receipt = store.ingest(input);
  const rebuilt = store.reconstruct(receipt);
  expect(rebuilt.length, `${label}: length`).toBe(input.length);
  // Compared as digests rather than element-by-element: a 256 KiB `toEqual` produces an unusable
  // diff on failure, while a digest mismatch plus the length above localizes it immediately.
  expect(digestChunkSync(rebuilt), `${label}: digest`).toBe(digestChunkSync(input));
}

/** Sum of every stored record's `storedBytes`, computed independently of the store's own counter. */
function sumStoredBytes(store: NetworkStore): number {
  let total = 0;
  for (const digest of store.digests()) {
    const record = store.recordFor(digest);
    expect(record, `record for ${digest}`).toBeDefined();
    if (record !== undefined) {
      total += record.storedBytes;
    }
  }
  return total;
}

describe('NetworkStore correctness — reconstruct(ingest(x)) === x', () => {
  it('round-trips the empty input', () => {
    const store = new NetworkStore();
    const receipt = store.ingest(new Uint8Array(0));
    expect(receipt.chunkDigests).toHaveLength(0);
    expect(receipt.totalBytes).toBe(0);
    expect(store.reconstruct(receipt)).toEqual(new Uint8Array(0));
    expect(store.stats().storedBytes).toBe(0);
    // Ratio is defined as 1, not NaN or Infinity, when nothing is stored.
    expect(store.stats().effectiveRatio).toBe(1);
  });

  it('round-trips a single byte and a sub-k-gram input', () => {
    const store = new NetworkStore();
    expectExactRoundTrip(store, new Uint8Array([0x00]), 'single zero byte');
    expectExactRoundTrip(store, new Uint8Array([0xff]), 'single ff byte');
    expectExactRoundTrip(store, noise(7, 11), '7 bytes (shorter than the 16-byte k-gram)');
    expectExactRoundTrip(store, noise(16, 12), 'exactly one k-gram');
  });

  it('round-trips inputs that straddle every chunking boundary rule', () => {
    const store = new NetworkStore();
    for (const length of [
      1,
      8 * 1024 - 1,
      8 * 1024,
      8 * 1024 + 1,
      32 * 1024,
      128 * 1024,
      128 * 1024 + 1,
      333_333,
    ]) {
      expectExactRoundTrip(store, noise(length, 0x51_0000 + length), `high-entropy ${length}B`);
    }
  });

  it('round-trips a large high-entropy input', () => {
    const store = new NetworkStore();
    const input = noise(1_000_000, 0xbeef);
    expectExactRoundTrip(store, input, '1 MB high-entropy');
    const stats = store.stats();
    expect(stats.chunks).toBeGreaterThan(1);
    expect(stats.verificationFallbacks).toBe(0);
  });

  it('round-trips highly repetitive input, and compresses it enormously', () => {
    const store = new NetworkStore();
    const input = repeating(512 * 1024, 251);
    expectExactRoundTrip(store, input, '512 KB repeating');
    const stats = store.stats();
    // Not a claim about the network effect — brotli alone does this. Asserted only so a
    // catastrophic regression in the storage path shows up here.
    expect(stats.effectiveRatio).toBeGreaterThan(10);
  });

  it('round-trips all-zero input', () => {
    const store = new NetworkStore();
    expectExactRoundTrip(store, new Uint8Array(300_000), '300 KB of zeros');
  });

  it('round-trips a full rendition ladder, source and every rung', () => {
    const store = new NetworkStore();
    const { source, renditions } = generateRenditionLadder(0x1ad_de7);
    expectExactRoundTrip(store, source, 'ladder source');
    renditions.forEach((rendition, index) => {
      expectExactRoundTrip(store, rendition, `ladder rung ${String(index)}`);
    });
    expect(store.stats().verificationFallbacks).toBe(0);
  });

  it('round-trips reaction and re-encode corpora ingested into one store', () => {
    const store = new NetworkStore();
    const { source } = generateRenditionLadder(0xc0_ffee, { gopCount: 3 });
    for (const [index, video] of generateReactionCorpus(0x9ea, {
      clip: source.subarray(0, 48 * 1024),
    }).entries()) {
      expectExactRoundTrip(store, video, `reaction ${String(index)}`);
    }
    for (const [index, variant] of generateReencodeVariants(0x5e7, { source }).entries()) {
      expectExactRoundTrip(store, variant, `variant ${String(index)}`);
    }
    expect(store.stats().verificationFallbacks).toBe(0);
  });

  it('reconstructs each chunk independently of the receipt it came from', () => {
    const store = new NetworkStore();
    const { source, renditions } = generateRenditionLadder(0x2b);
    store.ingest(source);
    const rendition = renditions[0];
    expect(rendition).toBeDefined();
    if (rendition === undefined) {
      return;
    }
    const receipt = store.ingest(rendition);
    // Resolve every chunk by digest alone and reassemble by hand: proves records are
    // self-contained addresses, not positions in a receipt.
    const parts = receipt.chunkDigests.map((digest) => store.resolveChunk(digest));
    const total = parts.reduce((sum, part) => sum + part.length, 0);
    const rebuilt = new Uint8Array(total);
    let offset = 0;
    for (const part of parts) {
      rebuilt.set(part, offset);
      offset += part.length;
    }
    expect(digestChunkSync(rebuilt)).toBe(digestChunkSync(rendition));
  });
});

describe('NetworkStore exact dedup', () => {
  it('adds precisely zero stored bytes when the same bytes are ingested twice', () => {
    const store = new NetworkStore();
    const input = generateRenditionLadder(0x777).source;

    const first = store.ingest(input);
    const afterFirst = store.stats();
    expect(first.newStoredBytes).toBeGreaterThan(0);
    expect(first.exactHits).toBe(0);

    const second = store.ingest(input);
    const afterSecond = store.stats();

    // The precise assertions the task asks for.
    expect(second.newStoredBytes).toBe(0);
    expect(second.dedupOnlyBytes).toBe(0);
    expect(second.deltaChunks).toBe(0);
    expect(second.standaloneChunks).toBe(0);
    expect(second.exactHits).toBe(first.chunkDigests.length);
    expect(afterSecond.storedBytes).toBe(afterFirst.storedBytes);
    expect(afterSecond.uniqueChunks).toBe(afterFirst.uniqueChunks);
    expect(afterSecond.dedupOnlyBytes).toBe(afterFirst.dedupOnlyBytes);
    // No similarity query is even attempted on an exact hit.
    expect(afterSecond.similarityQueries).toBe(afterFirst.similarityQueries);
    // Ingested bytes doubled while stored bytes did not move: the ratio exactly doubled.
    expect(afterSecond.ingestedBytes).toBe(afterFirst.ingestedBytes * 2);
    expect(afterSecond.effectiveRatio).toBeCloseTo(afterFirst.effectiveRatio * 2, 10);
    expect(digestChunkSync(store.reconstruct(second))).toBe(digestChunkSync(input));
  });

  it('gives identical digests for identical chunks reached at different offsets', () => {
    const store = new NetworkStore();
    const videos = generateReactionCorpus(0x1a1a);
    for (const video of videos) {
      store.ingest(video);
    }
    const stats = store.stats();
    // The shared clip is 64 KiB and staggered, so content-defined chunking realigns on it and at
    // least one whole chunk of it recurs byte-identically across uploads. This is dedup's win, not
    // delta's, and the test says so.
    expect(stats.exactHits).toBeGreaterThan(0);
  });
});

describe('NetworkStore similarity delta beats dedup-only on a rendition ladder', () => {
  it('produces delta chunks and a strictly better ratio than dedup alone', () => {
    const store = new NetworkStore();
    const { source, renditions } = generateRenditionLadder(0x1_2345);
    const uploads = [source, ...renditions];
    for (const upload of uploads) {
      const receipt = store.ingest(upload);
      expect(digestChunkSync(store.reconstruct(receipt))).toBe(digestChunkSync(upload));
    }

    const stats = store.stats();
    const dedupOnlyRatio = stats.ingestedBytes / stats.dedupOnlyBytes;

    console.log(
      [
        '',
        'rendition ladder, 1 source + 3 rungs:',
        `  ingested bytes        ${String(stats.ingestedBytes)}`,
        `  dedup-only bytes      ${String(stats.dedupOnlyBytes)}  ratio ${dedupOnlyRatio.toFixed(3)}`,
        `  middle-out bytes      ${String(stats.storedBytes)}  ratio ${stats.effectiveRatio.toFixed(3)}`,
        `  delta bytes saved     ${String(stats.deltaBytesSaved)}`,
        `  chunks                ${String(stats.chunks)} (exact ${String(stats.exactHits)}, ` +
          `delta ${String(stats.deltaChunks)}, standalone ${String(stats.standaloneChunks)})`,
        `  depth histogram       ${JSON.stringify(store.depthHistogram())}`,
        `  mean candidates/query ${stats.meanCandidatesPerQuery.toFixed(2)}`,
        '',
      ].join('\n'),
    );

    expect(stats.deltaChunks).toBeGreaterThan(0);
    expect(stats.effectiveRatio).toBeGreaterThan(dedupOnlyRatio);
    expect(stats.storedBytes).toBeLessThan(stats.dedupOnlyBytes);
    expect(stats.deltaBytesSaved).toBeGreaterThan(0);
    expect(stats.verificationFallbacks).toBe(0);
  });

  it('never loses to standalone compression, per record', () => {
    const store = new NetworkStore();
    // A deliberately hostile mix: incompressible and mutually dissimilar chunks, where delta
    // cannot help and must therefore stand aside.
    for (let index = 0; index < 4; index += 1) {
      store.ingest(noise(120 * 1024, 0xaaa0 + index));
    }
    const { source, renditions } = generateRenditionLadder(0x9_1111);
    store.ingest(source);
    for (const rendition of renditions) {
      store.ingest(rendition);
    }

    for (const digest of store.digests()) {
      const record = store.recordFor(digest);
      expect(record).toBeDefined();
      if (record === undefined) {
        continue;
      }
      // The never-worse guarantee, checked on every single stored record.
      expect(record.storedBytes).toBeLessThanOrEqual(record.standaloneBaselineBytes);
      if (record.kind === 'delta') {
        // A delta is only ever stored when it is *strictly* smaller, pointer included.
        expect(record.storedBytes).toBeLessThan(record.standaloneBaselineBytes);
        expect(record.payload.length + REFERENCE_POINTER_BYTES).toBe(record.storedBytes);
        expect(record.referenceDigest).not.toBeNull();
      } else {
        expect(record.payload.length).toBe(record.storedBytes);
        expect(record.referenceDigest).toBeNull();
        expect(record.depth).toBe(0);
      }
    }
    expect(store.stats().storedBytes).toBeLessThanOrEqual(store.stats().dedupOnlyBytes);
  });

  it('reports honestly that pure noise gains nothing from similarity delta', () => {
    const store = new NetworkStore();
    let ingested = 0;
    for (let index = 0; index < 6; index += 1) {
      const input = noise(96 * 1024, 0x4_0000 + index * 7919);
      ingested += input.length;
      const receipt = store.ingest(input);
      expect(digestChunkSync(store.reconstruct(receipt))).toBe(digestChunkSync(input));
    }
    const stats = store.stats();
    expect(stats.ingestedBytes).toBe(ingested);
    // Random bytes are incompressible and dissimilar by construction: no chunk shares k-grams
    // with any other, so the index finds nothing, every chunk goes standalone, and brotli cannot
    // shrink it either. The honest result is a ratio of essentially exactly 1.
    expect(stats.deltaChunks).toBe(0);
    expect(stats.exactHits).toBe(0);
    expect(stats.standaloneChunks).toBe(stats.uniqueChunks);
    expect(stats.effectiveRatio).toBeLessThan(1.001);
    expect(stats.effectiveRatio).toBeGreaterThan(0.999);
    expect(stats.deltaBytesSaved).toBe(0);
  });
});

describe('NetworkStore delta chains', () => {
  it('bounds chain depth, terminates every chain in a standalone, and still reconstructs', () => {
    const store = new NetworkStore();
    // Six rungs, each derived from the same blocks, ingested in order: exactly the shape that
    // tempts the store into a long chain, since rung n resembles rung n-1 most.
    const { source, renditions } = generateRenditionLadder(0xc4a1, {
      renditionCount: 6,
      retention: 0.93,
    });
    const uploads = [source, ...renditions];
    const receipts = uploads.map((upload) => store.ingest(upload));

    const histogram = store.depthHistogram();
    expect(histogram).toHaveLength(DEFAULT_MAX_CHAIN_DEPTH + 1);
    for (const digest of store.digests()) {
      const record = store.recordFor(digest);
      expect(record).toBeDefined();
      if (record === undefined) {
        continue;
      }
      expect(record.depth).toBeGreaterThanOrEqual(0);
      expect(record.depth).toBeLessThanOrEqual(DEFAULT_MAX_CHAIN_DEPTH);

      // Walk to the root by hand: proves acyclicity and termination independently of resolveChunk.
      const seen = new Set<string>([digest]);
      let cursor = record.referenceDigest;
      let steps = 0;
      while (cursor !== null) {
        expect(seen.has(cursor), `cycle at ${cursor}`).toBe(false);
        seen.add(cursor);
        const next = store.recordFor(cursor);
        expect(next, `reference ${cursor} must be stored`).toBeDefined();
        if (next === undefined) {
          break;
        }
        steps += 1;
        expect(steps).toBeLessThanOrEqual(DEFAULT_MAX_CHAIN_DEPTH);
        cursor = next.referenceDigest;
      }
      expect(steps).toBe(record.depth);
    }

    uploads.forEach((upload, index) => {
      const receipt = receipts[index];
      expect(receipt).toBeDefined();
      if (receipt !== undefined) {
        expect(digestChunkSync(store.reconstruct(receipt))).toBe(digestChunkSync(upload));
      }
    });
    expect(store.stats().maxObservedChainDepth).toBeLessThanOrEqual(DEFAULT_MAX_CHAIN_DEPTH);
    expect(store.stats().verificationFallbacks).toBe(0);
  });

  it('honours a tightened depth bound and a disabled delta path', () => {
    const { source, renditions } = generateRenditionLadder(0x3_9999, { renditionCount: 4 });
    const uploads = [source, ...renditions];

    const flat = new NetworkStore({ maxChainDepth: 1 });
    for (const upload of uploads) {
      const receipt = flat.ingest(upload);
      expect(digestChunkSync(flat.reconstruct(receipt))).toBe(digestChunkSync(upload));
    }
    expect(flat.stats().maxObservedChainDepth).toBeLessThanOrEqual(1);
    expect(flat.depthHistogram()).toHaveLength(2);
    for (const digest of flat.digests()) {
      const record = flat.recordFor(digest);
      if (record?.referenceDigest != null) {
        expect(flat.recordFor(record.referenceDigest)?.kind).toBe('standalone');
      }
    }

    // maxChainDepth 0 disables delta entirely: the store degenerates to dedup + brotli, which is
    // the baseline strategy (b), and must still be byte-exact.
    const dedupOnly = new NetworkStore({ maxChainDepth: 0 });
    for (const upload of uploads) {
      const receipt = dedupOnly.ingest(upload);
      expect(digestChunkSync(dedupOnly.reconstruct(receipt))).toBe(digestChunkSync(upload));
    }
    const stats = dedupOnly.stats();
    expect(stats.deltaChunks).toBe(0);
    expect(stats.similarityQueries).toBe(0);
    expect(stats.storedBytes).toBe(stats.dedupOnlyBytes);
    expect(stats.deltaBytesSaved).toBe(0);
    // And the full store must beat it on the very same input.
    const full = new NetworkStore();
    for (const upload of uploads) {
      full.ingest(upload);
    }
    expect(full.stats().storedBytes).toBeLessThan(stats.storedBytes);
  });

  it('rejects a receipt whose chunks are not in the store', () => {
    const donor = new NetworkStore();
    const receipt = donor.ingest(noise(64 * 1024, 0x1234));
    const empty = new NetworkStore();
    expect(() => empty.reconstruct(receipt)).toThrow(NetworkStoreError);
    expect(() => empty.resolveChunk('0'.repeat(64))).toThrow(NetworkStoreError);
  });

  it('rejects a receipt whose declared length disagrees with its chunks', () => {
    const store = new NetworkStore();
    const receipt = store.ingest(noise(40 * 1024, 0x4321));
    expect(() => store.reconstruct({ ...receipt, totalBytes: receipt.totalBytes - 1 })).toThrow(
      NetworkStoreError,
    );
    expect(() => store.reconstruct({ ...receipt, totalBytes: receipt.totalBytes + 1 })).toThrow(
      NetworkStoreError,
    );
  });
});

describe('NetworkStore stats arithmetic is self-consistent', () => {
  it('balances every counter against independently recomputed values', () => {
    const store = new NetworkStore();
    const { source, renditions } = generateRenditionLadder(0x5_1a75);
    const uploads = [
      source,
      ...renditions,
      ...generateReencodeVariants(0x5_1a76, { source, variantCount: 3 }),
      ...generateReactionCorpus(0x5_1a77, { clip: source.subarray(0, 40 * 1024), videoCount: 3 }),
      noise(80 * 1024, 0x5_1a78),
      source, // re-ingest: exercises the exact-hit path inside a mixed corpus
    ];

    let expectedIngested = 0;
    let expectedChunkRefs = 0;
    let receiptStored = 0;
    let receiptDedupOnly = 0;
    let receiptExact = 0;
    let receiptDelta = 0;
    let receiptStandalone = 0;

    for (const upload of uploads) {
      const receipt = store.ingest(upload);
      expectedIngested += upload.length;
      expectedChunkRefs += chunkBytes(upload).length;
      receiptStored += receipt.newStoredBytes;
      receiptDedupOnly += receipt.dedupOnlyBytes;
      receiptExact += receipt.exactHits;
      receiptDelta += receipt.deltaChunks;
      receiptStandalone += receipt.standaloneChunks;
      expect(receipt.chunkDigests).toHaveLength(chunkBytes(upload).length);
      expect(receipt.exactHits + receipt.deltaChunks + receipt.standaloneChunks).toBe(
        receipt.chunkDigests.length,
      );
    }

    const stats = store.stats();

    expect(stats.ingestedBytes).toBe(expectedIngested);
    expect(stats.chunks).toBe(expectedChunkRefs);
    expect(stats.chunks).toBe(stats.exactHits + stats.deltaChunks + stats.standaloneChunks);
    expect(stats.uniqueChunks).toBe(stats.deltaChunks + stats.standaloneChunks);
    expect(stats.uniqueChunks).toBe(store.digests().length);
    expect(stats.indexSize).toBe(stats.uniqueChunks);

    // Receipts must sum to the cumulative counters exactly.
    expect(stats.storedBytes).toBe(receiptStored);
    expect(stats.dedupOnlyBytes).toBe(receiptDedupOnly);
    expect(stats.exactHits).toBe(receiptExact);
    expect(stats.deltaChunks).toBe(receiptDelta);
    expect(stats.standaloneChunks).toBe(receiptStandalone);

    // And the counter must agree with a walk over the records themselves.
    expect(stats.storedBytes).toBe(sumStoredBytes(store));

    expect(stats.deltaBytesSaved).toBe(stats.dedupOnlyBytes - stats.storedBytes);
    expect(stats.deltaBytesSaved).toBeGreaterThanOrEqual(0);
    expect(stats.effectiveRatio).toBeCloseTo(stats.ingestedBytes / stats.storedBytes, 10);
    expect(stats.manifestBytes).toBe(stats.chunks * REFERENCE_POINTER_BYTES);
    expect(stats.storedBytesWithManifest).toBe(stats.storedBytes + stats.manifestBytes);
    expect(stats.similarityQueries).toBe(stats.uniqueChunks);
    expect(stats.meanCandidatesPerQuery).toBeCloseTo(
      stats.similarityCandidatesExamined / stats.similarityQueries,
      10,
    );
    expect(store.depthHistogram().reduce((sum, count) => sum + count, 0)).toBe(stats.uniqueChunks);
    expect(stats.verificationFallbacks).toBe(0);
    expect(stats.exactHits).toBeGreaterThan(0);
    expect(stats.deltaChunks).toBeGreaterThan(0);
  });

  it('validates its options instead of misbehaving later', () => {
    expect(() => new NetworkStore({ maxChainDepth: -1 })).toThrow(NetworkStoreError);
    expect(() => new NetworkStore({ maxChainDepth: 1.5 })).toThrow(NetworkStoreError);
    expect(() => new NetworkStore({ referenceCandidates: -1 })).toThrow(NetworkStoreError);
    // A sketch size given only for sketching must be threaded into the index's banding, not
    // silently validated against the default.
    expect(() => new NetworkStore({ sketch: { sketchSize: 32 } })).not.toThrow();
    const store = new NetworkStore({
      sketch: { sketchSize: 32 },
      index: { bands: 8, rowsPerBand: 4 },
    });
    const receipt = store.ingest(generateRenditionLadder(0x6_0001, { gopCount: 2 }).source);
    expect(digestChunkSync(store.reconstruct(receipt))).not.toBe('');
  });
});

describe('media corpus generators', () => {
  it('are deterministic and produce similar-but-not-identical outputs', () => {
    const a = generateRenditionLadder(0x0ab1);
    const b = generateRenditionLadder(0x0ab1);
    expect(digestChunkSync(a.source)).toBe(digestChunkSync(b.source));
    a.renditions.forEach((rendition, index) => {
      const other = b.renditions[index];
      expect(other).toBeDefined();
      if (other !== undefined) {
        expect(digestChunkSync(rendition)).toBe(digestChunkSync(other));
      }
      // Similar but NOT identical is the whole point: identical would be caught by exact dedup
      // and would prove nothing about delta.
      expect(digestChunkSync(rendition)).not.toBe(digestChunkSync(a.source));
      expect(rendition.length).toBeLessThan(a.source.length);
    });
  });

  it('embeds a byte-identical clip in every reaction video', () => {
    const clip = noise(20 * 1024, 0x0c11);
    const videos = generateReactionCorpus(0x0bee, { clip, videoCount: 3 });
    const clipDigest = digestChunkSync(clip);
    for (const video of videos) {
      let found = false;
      for (let offset = 0; offset + clip.length <= video.length; offset += 1) {
        if (video[offset] === clip[0]) {
          const window = video.subarray(offset, offset + clip.length);
          if (digestChunkSync(window) === clipDigest) {
            found = true;
            break;
          }
        }
      }
      expect(found).toBe(true);
    }
  });

  it('keeps re-encode variants distinct, similar to the master, and length-shifted', () => {
    const master = noise(64 * 1024, 0x0d00);
    const variants = generateReencodeVariants(0x0d01, { source: master });
    const seen = new Set<string>([digestChunkSync(master)]);
    for (const variant of variants) {
      expect(seen.has(digestChunkSync(variant))).toBe(false);
      seen.add(digestChunkSync(variant));
      expect(variant.length).toBeGreaterThan(master.length);
    }
  });

  it('rejects unusable options', () => {
    expect(() => generateRenditionLadder(1, { gopCount: 0 })).toThrow(MediaCorpusError);
    expect(() => generateRenditionLadder(1, { retention: 1 })).toThrow(MediaCorpusError);
    expect(() => generateRenditionLadder(1, { gopBytes: 1000, subBlocksPerGop: 3 })).toThrow(
      MediaCorpusError,
    );
    expect(() => generateReactionCorpus(1, { clipBytes: -1 })).toThrow(MediaCorpusError);
    expect(() => generateReencodeVariants(1, { divergencePerStep: 0 })).toThrow(MediaCorpusError);
    expect(() => generateReencodeVariants(1, { shiftEdits: -1 })).toThrow(MediaCorpusError);
    expect(() => generateRenditionLadder(1.5)).toThrow(MediaCorpusError);
  });
});
